<a href="https://colab.research.google.com/github/Clownessa/Python-course-/blob/master/Practice_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#task 1 low
#Create a 8x8 matrix and fill it with a checkerboard pattern. 
#(NOTE: without loops!)

import numpy as np

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [0]:
#task 2
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area. 
#(NOTE: without loops!)

import numpy as np

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [0]:
#task 3
#Consider a random 10x2 matrix representing cartesian coordinates 
#(10 points on a plane), convert them to polar coordinates.
#(NOTE: without loops!)

import numpy as np

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.88606069 0.86081935 0.6292706  0.20309672 0.3195305  0.55166599
 0.8921849  0.91112718 1.16899929 0.8792869 ]
[0.88782937 0.08813068 1.14452789 1.29659433 1.44133852 0.89557485
 1.31955567 0.55411651 0.94206644 1.01841671]


In [0]:
#task 4
#Find the nearest value N from a given value A in an array X.
#(NOTE: without loops!)

import numpy as np

X = np.array([1, 2, 3, 4, 5, 6])
A = 2.4685
# Находим индекс ближайшего к A элемента
index = (np.abs(X-A)).argmin()
print(X[index])

2


In [0]:
#task 5
#Subtract the mean of each row of a matrix (elementwise).
#(NOTE: without loops!)

import numpy as np

X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.27654028  0.13242076  0.11445999  0.47918357 -0.48273408 -0.40387268
   0.33943727  0.17383353 -0.03780965 -0.03837844]
 [ 0.42595856  0.22597953 -0.07601923  0.38121963 -0.41701129 -0.3073656
  -0.33662659 -0.39977456  0.40684841  0.09679115]
 [-0.16824154  0.30013453  0.17557309 -0.33579305 -0.28352049  0.33666342
   0.37184907  0.36556987 -0.39510844 -0.36712646]
 [-0.42625873 -0.38790493 -0.27981061  0.44990946  0.08947607 -0.33525488
   0.36134708  0.15007089  0.28199064  0.09643501]
 [ 0.22286674 -0.20713561  0.00745788  0.15884137  0.15108963  0.12230417
   0.02759144 -0.37154408  0.22045134 -0.33192287]]


In [0]:
#task 6
#Randomly place p given elements in a 2D array of zeros.
#(NOTE: without loops!)

import numpy as np

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
#task 7
#How to accumulate elements of a vector (X) to an array (F) 
#based on an index list (I)? 
#(It's okay, if you will use loops)


import numpy as np

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [0]:
#task 1 medium
#How to swap two rows of a given 2-dim matrix of an array? 
#(in just one step)

import numpy as np

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [0]:
#task 2
#Find all null (with zeros only) columns in a given 
#multi dimensional array and print its indices.
#(NOTE: without loops!)

import numpy as np

matrix = np.array([[0, 0, 0],
[0, 1, 0],
[0, 0, 0],
[0, 0, 0]])

coordinates = np.transpose(np.argwhere(matrix))[1]
a = np.arange(matrix.shape[1])

coordinates = np.array(set(a) - set(coordinates))
print(coordinates)

{0, 2}


In [0]:
#task 3
#Consider the vector, how to build a new vector with 3 consecutive 
#zeros interleaved between each value?
#(NOTE: without loops!)

import numpy as np

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [0]:
#task 4
#Given an arbitrary number of vectors, build the cartesian product
#(every combinations of every item).
#(Loops allowed, but use NumPy!)

import numpy as np

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [0]:
#task 5
#How to compute averages using a sliding window (of a given size N) over an array Z?

import numpy as np

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [0]:
#task 1 advanced 
#Considering a four dimensional array, how to get the sum over the last two axes at once?
import numpy as np

A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[29 41 68 53]
 [58 71 62 57]
 [57 54 67 54]]
[[29 41 68 53]
 [58 71 62 57]
 [57 54 67 54]]


In [0]:
#task 2
#An image can be represented as a 3-dim array: (height, width, channels). 
#How to compute the number of unique colors in an image? 
#NOTE: One color - combination of 3 channels: Red, Green, Blue
#(Find some info about RGB image representation in the Internet!)

import numpy as np

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [0]:
#task 3
#Consider a random vector with shape (100,2) representing coordinates, 
#find point by point distances (Try it without loops!)

import numpy as np

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.09225482 0.1209855  0.7614664  0.59672352 0.27843566
  0.60163829 0.38798863 0.71847264 0.94164578]
 [0.09225482 0.         0.1874268  0.77536341 0.59311492 0.18665157
  0.62734344 0.4687141  0.6882411  0.90235162]
 [0.1209855  0.1874268  0.         0.86037512 0.7076268  0.36454565
  0.69319167 0.40568182 0.83794143 1.06227358]
 [0.7614664  0.77536341 0.86037512 0.         0.21622071 0.81309462
  0.17861594 0.60988675 0.35908526 0.51394095]
 [0.59672352 0.59311492 0.7076268  0.21622071 0.         0.60649304
  0.19453251 0.55486755 0.21885379 0.44080251]
 [0.27843566 0.18665157 0.36454565 0.81309462 0.60649304 0.
  0.69415446 0.63324104 0.64009417 0.82605473]
 [0.60163829 0.62734344 0.69319167 0.17861594 0.19453251 0.69415446
  0.         0.43317403 0.4085721  0.61470604]
 [0.38798863 0.4687141  0.40568182 0.60988675 0.55486755 0.63324104
  0.43317403 0.         0.75841344 0.99106747]
 [0.71847264 0.6882411  0.83794143 0.35908526 0.21885379 0.64009417
  0.4085721  0.75841

In [0]:
#task 4
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p,
#how to compute distance from p to each line i (P0[i],P1[i])?

import numpy as np

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.75949201 13.49258373  3.01410565  8.61224533 18.57677507  4.32129587
 11.48620894  3.13315103 12.48014799  7.92022247]


In [0]:
#task 5
#Convert a vector of ints into a matrix binary representation 
#(NOTE: without loops!)

import numpy as np

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
